### ISSUE TITLE
简体字版本

### ISSUE THREAD

**Issue by onlyloveyd** [KomaBeyond/chinese-poetry-mysql#1]
请问这个有简体字版本嘛？

**Comment by Kooooooma** [comment]
@onlyloveyd 有个简体版的库 https://github.com/chinese-poetry/chinese-poetry-zhCN

我这里没有，我在等主库的标签系统完善，到时候会一起升级增加

**Comment by onlyloveyd** [comment]
@KomaBeyond 主库上貌似还是繁体

![tim 20180413140441](https://user-images.githubusercontent.com/7044935/38719308-c81bff70-3f23-11e8-9519-106777e9667d.png)

**Comment by Kooooooma** [comment]
@onlyloveyd 对，他应该还在弄标签那块儿，原始数据一部分是繁体，一部分是简体，等他标签系统完善出来之后我会把我告诉你的那个简体库和原始数据结合一下，方便使用，不想升级太多次，所以就在等标签完善好再一起弄一下

**Comment by onlyloveyd** [comment]
@KomaBeyond OK. 3ks 我是想弄个数据接口出来
