### ISSUE TITLE
sql脚本打开后乱码

### ISSUE THREAD

**Issue by gaozhy996** [KomaBeyond/chinese-poetry-mysql#3]

**Comment by Kooooooma** [comment]
具体情况说明一下 @gaozhy520

**Comment by canaanpaul** [comment]
function doExecute($sql) {
    global $db;
    mysqli_set_charset($db,"utf8");//加上这句
    // $db->set_charset("utf8");

    if (!$db->query($sql)) {
        die("Query Error: ".mysqli_error($db));
    }
}

**Comment by Kooooooma** [comment]
参考最新更新的 sql 压缩数据导出及回放步骤说明，可以解决乱码问题。如果在数据库中依然是乱码，可以直接使用脚本生成数据到数据库中。
