### ISSUE TITLE
导入之后全是乱码

### ISSUE THREAD

**Issue by windyboyy** [KomaBeyond/chinese-poetry-mysql#5]
有什么解决方法吗，编码格式是啥

**Comment by xuemodotaer** [comment]
数据库文件下载下来中文全是乱码，换了几个编码方式保存都没有，有办法解决吗

**Comment by Kooooooma** [comment]
参考最新更新的 sql 压缩数据导出及回放步骤说明，可以解决乱码问题。如果在数据库中依然是乱码，可以直接使用脚本生成数据到数据库中。

**Comment by xuemodotaer** [comment]
谢谢，我直接把上面的json文件全部下载下来，然后解析入库了




------------------ 原始邮件 ------------------
发件人: "Koma|张强"<notifications@github.com>;
发送时间: 2019年4月12日(星期五) 上午9:53
收件人: "KomaBeyond/chinese-poetry-mysql"<chinese-poetry-mysql@noreply.github.com>;
抄送: "364575658"<364575658@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [KomaBeyond/chinese-poetry-mysql] 导入之后全是乱码 (#5)




参考最新更新的 sql 压缩数据导出及回放步骤说明，可以解决乱码问题。如果在数据库中依然是乱码，可以直接使用脚本生成数据到数据库中。
